### Homework 1

First, we import the necessary libraries

In [54]:
import pandas as pd
import os
import numpy as np

### Q1

We check the version of pandas

In [5]:
print(pd.__version__)

2.3.1

Now we import the data

In [7]:
path = os.path.join("data", "car_fuel_efficiency_2026.csv")

df = pd.read_csv(path)
print(df.head(5))

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4
1        2008  Europe    Diesel  Front-wheel drive          4
2        1996    Asia  Gasoline  Front-wheel drive          5
3        1989  Europe  Gasoline  Front-wheel drive          4
4        1994     USA    Diesel  Front-wheel drive          3

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870
1                 2390              6       272.0            4210
2                 2320              6       267.0            4240
3                 2130              6       258.0            4490
4                 2580              7       304.0            4510

   acceleration  fuel_efficiency_mpg
0           NaN                 31.9
1           NaN                 31.3
2          17.3                 27.5
3          18.7                 28.5
4          17.5                 31.0

### Q2

In [ ]:
print(df.shape) # this returns (# row, # columns)

(10000, 11)

### Q3

In [19]:
print(df["fuel_type"].nunique())
print(df["fuel_type"].unique())

3
['Gasoline' 'Diesel' 'Hybrid']

### Q4

In [25]:
print(df.isnull().sum()) # This method, counts the True variables as 1 and the False ones as 0, so it sums the  value over each column

df.isnull().sum().sum() # Now we sum over the only column left and returns the total number of nulls in the data set

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

np.int64(1141)

### Q5

In [ ]:
# Groupby indicates that the different origins must be treated separately at the time of calculating the maximum
df.groupby("origin")["fuel_efficiency_mpg"].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

### Q6

In [32]:
df["horsepower"].median()

np.float64(254.0)

In [38]:
# For the most frequent value we use:
print(df["horsepower"].mode()) # dataframe
frequent_number = df["horsepower"].mode()[0] # Float Number

0    252.0
Name: horsepower, dtype: float64

In [42]:
# Now fe fill the Nulls with the most frquent value
df["horsepower"].fillna(frequent_number)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [43]:
# Now we again calculate the median value:
df["horsepower"].fillna(frequent_number).median()

np.float64(252.0)

### Q7

In [46]:
# Now we extract only the cars form asia:

df_asia = df[df["origin"] == "Asia"]
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [49]:
df_asia_cut = df_asia[["vehicle_weight", "model_year"]]
df_asia_cut.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [51]:
df_asia_cut_2 = df_asia_cut.head(7)
print(df_asia_cut_2)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [55]:
# We creat the 2-dimensional array:
X = df_asia_cut_2.to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [58]:
XTX = np.dot(X.T, X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [59]:
inverse = np.linalg.inv(XTX)
print(inverse)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [60]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
temp = np.dot(inverse, X.T)
print(temp)
w=np.dot(temp, y)
print(w)

print(np.sum(w))

[[-2.50082897e-04 -1.65786806e-05 -2.86196661e-04  3.99964853e-04
  -1.18162927e-03  1.10298508e-03  2.25354894e-04]
 [ 6.12974614e-04  1.06954785e-04  6.91249245e-04 -7.95968736e-04
   2.63152339e-03 -2.31749941e-03 -4.16221392e-04]]
[0.13644777 0.2327492 ]
0.36919696904925486